### PR TITLE
Flush ready messages from foregone futures

### LINKED ISSUE #31: Ready messages can leak from wait/1 - transaction retry
Ready messages can leak from the erlfdb API when a transaction's UserFun is executed for a second time, after a retriable error. It can be reproduced with this contrived example:

```erlang
-module(erlfdb_tx_retry_leak).

-export([start/0]).

start() ->
    {ok, C} = application:get_env(erlfdb_tx_retry_leak, cluster_file),
    Db = erlfdb:open(C),

    io:format("Writing some data~n", []),
    [ erlfdb:set(Db, erlfdb_tuple:pack({<<"jms">>, I}), <<"test">>) || I <- lists:seq(1, 100) ],

    try
        erlfdb:transactional(Db,
                              fun(Tx) ->
                                      case put(allow_completion, true) of
                                          undefined ->
                                              io:format("Entering long 'get' loop~n", []),
                                              N = 6,
                                              fun Loop(10) -> ok; Loop(I) ->
                                                      S = I*N + 1,
                                                      Seq = lists:seq(S, S+N-1),
                                                      io:format("  => iteration ~p: ~p~n", [I, Seq]),
                                                      Futures = [ erlfdb:get(Tx, erlfdb_tuple:pack({<<"jms">>, X})) || X <- Seq],
                                                      erlfdb:wait_for_all(Futures),
                                                      timer:sleep(1000),
                                                      Loop(I+1)
                                              end(0);
                                          true ->
                                              io:format("Now in transaction retry~n", []),
                                              erlfdb:wait(erlfdb:get(Tx, <<"hello">>)),
                                              io:format("Finishing transaction~n", [])
                                      end
                              end)
    after
              erase(allow_completion)
    end,

    timer:sleep(1000),

    io:format("Flushing message queue~n", []),
    Leaks = fun FlushReady(Acc) ->
            receive
                Msg={_Ref, ready} ->
                    FlushReady([Msg|Acc])
            after 0 ->
                 lists:reverse(Acc)
            end
    end([]),

    [] = Leaks,

    Db.
```

Output:
```bash
1> erlfdb_tx_retry_leak:start().
Writing some data
Entering long 'get' loop
  => iteration 0: [1,2,3,4,5,6]
  => iteration 1: [7,8,9,10,11,12]
  => iteration 2: [13,14,15,16,17,18]
  => iteration 3: [19,20,21,22,23,24]
  => iteration 4: [25,26,27,28,29,30]
  => iteration 5: [31,32,33,34,35,36]
  => iteration 6: "%&'()*"
  => iteration 7: "+,-./0"
Now in transaction retry
Finishing transaction
Flushing message queue
** exception error: no match of right hand side value [{#Ref<0.3346802005.2444492801.68320>,ready},
                                                       {#Ref<0.3346802005.2444492801.68322>,ready},
                                                       {#Ref<0.3346802005.2444492801.68324>,ready},
                                                       {#Ref<0.3346802005.2444492801.68326>,ready},
                                                       {#Ref<0.3346802005.2444492801.68328>,ready}]
     in function  erlfdb_tx_retry_leak:start/0 (/Users/jstimpson/dev/erlang/erlfdb_tx_retry_leak/src/erlfdb_tx_retry_leak.erl, line 50)
```

### PR DESCRIPTION
**Pull request by jessestimpson**
Closes #31 

Ready message for a watch remains of the form `{reference(), ready}`.

All other interactions will present `{{TxRef :: reference(), reference()}, ready}`.

When a transaction does not complete successfully on the first attempt, a flush is made for any remaining ready messages on the message queue.

A unit test exercises this with a fake not_committed error.

### CODE REVIEW

File: src/erlfdb.erl [hunk 1]
```diff
@@ -1903,6 +1911,15 @@ do_transaction(?IS_TX = Tx, UserFun) ->
             put(?ERLFDB_ERROR, Code),
             wait(on_error(Tx, Code), [{timeout, infinity}]),
             do_transaction(Tx, UserFun)
+    after
```
Comment (jessestimpson) [inline src/erlfdb.erl]: This is a bit awkward as it will run for each do_transaction. If the UserFun is run more than twice, the flush runs more than once. We could introduce a `Depth` var in do_transaction that would allow us to ensure the flush only runs once, but increases the code complexity a bit.

```erlang
after
    case {Depth, erlang:get(?ERLFDB_ERROR)} of
        {_, undefined} -> ok;
        {1, _} -> flush_transaction_ready_messages(Tx);
        _ -> ok
    end
end
```

Comment (jessestimpson) [reply src/erlfdb.erl]: After thinking about this a bit more, using an `after` like this will blow out the stack frame. We should move the logic into the catch and we will have to introduce a `Depth` to ensure all other recursive `do_transaction`s remain tail calls.
