### PR TITLE
Fix future cancelation deadlock

### LINKED ISSUE #59: Unable to cancel a future
Both of these attempts to cancel a future usually result in a deadlock.

```erlang
1> Db = erlfdb:open(<<"/etc/foundationdb/fdb.cluster">>).
{erlfdb_database,#Ref<0.3399967816.4238999553.226012>}
2> erlfdb:transactional(Db, fun(Tx) -> Future = erlfdb:get(Tx, <<"foo">>), erlfdb:cancel(Future) end).
```

```erlang
1> Db = erlfdb:open(<<"/etc/foundationdb/fdb.cluster">>).
{erlfdb_database,#Ref<0.1432698195.212467716.235223>}
2> Future = erlfdb:watch(Db, <<"foo">>).
{erlfdb_future,#Ref<0.1432698195.212336645.241681>,
               #Ref<0.1432698195.212467717.241682>}
3> erlfdb:cancel(Future).
```

The reason is:

1. erlfdb_future_cancel locks the mutex
2. the execution of `fdb_future_cancel` makes a call to the callback
3. erlfdb_future_cb tries to lock the mutex

I have also observed the callback executing on the network thread, in which case the deadlock does not happen, but that seems to be rare.

### PR DESCRIPTION
**Pull request by jessestimpson**
Fixes #59

### CODE REVIEW

File: c_src/main.c [hunk 1]
```diff
@@ -2430,8 +2431,7 @@ static ERL_NIF_TERM erlfdb_error_predicate(ErlNifEnv *env, int argc,
     }
 }
 
-#define NIF_FUNC(name, arity)                                                  \
-    { #name, arity, name }
+#define NIF_FUNC(name, arity) {#name, arity, name}
```
Comment (jessestimpson) [inline c_src/main.c:2493]: This change was made to satisfy clang-format. Something must have changed with the ci formatter to make this a requirement now, whereas previously it was not.
